//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusHackServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allergy2User
    {
        public int AllergyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string DragName { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
