//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusHackServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangerousDrugCombination
    {
        public int CombinationId { get; set; }
        public string FirstDrugName { get; set; }
        public string SecondDrugName { get; set; }
    }
}
