//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusHackServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drug()
        {
            this.TimetablePush = new HashSet<TimetablePush>();
        }
    
        public int DrugId { get; set; }
        public int PatientId { get; set; }
        public string Name { get; set; }
        public string DrugType { get; set; }
        public string FrequencyAdmission { get; set; }
        public string FeaturesReception { get; set; }
        public Nullable<System.DateTime> StartReception { get; set; }
        public Nullable<System.DateTime> FinishReception { get; set; }
        public Nullable<bool> Allowed { get; set; }
        public Nullable<int> Period { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimetablePush> TimetablePush { get; set; }
    }
}
