//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusHackServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measuring
    {
        public int MeasuringId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int PatientId { get; set; }
        public Nullable<float> Temp { get; set; }
        public string Pressure { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
