//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusHackServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int ObjectId { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public string Link { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
