//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusHackServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimetablePush
    {
        public int TimetableId { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> DrugId { get; set; }
    
        public virtual Drug Drug { get; set; }
    }
}
