//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusHackServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenPush
    {
        public int TokenId { get; set; }
        public string Token { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
