//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusHackServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class User2Role
    {
        public int User2RoleId { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual User2Role User2Role1 { get; set; }
        public virtual User2Role User2Role2 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
